services:
  postgres:
    image: postgres:16
    container_name: bigdata_snowflake
    environment:
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: bigdata123
      POSTGRES_DB: petstore
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./исходные данные:/data
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bigdata -d petstore"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
